# This workflow will run tests using bun and then publish a package to NPM registry when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}\nregistry=https://registry.npmjs.org/\nalways-auth=true" > ~/.npmrc
      - run: npm publish
